name: teaching
channels: 
  - conda-forge
dependencies:
  - python=3.10           # Ensure consistent Python version
  - obspy
  - ipympl
  - nbgitpuller
  - numpy
  - matplotlib
  - cartopy         # added
  - jupyterlab            # Include JupyterLab for a richer interface
  - notebook              # Include classic notebook support
  - ipywidgets            # Needed for interactive widgets
